# Generated by Django 5.2 on 2025-05-07 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
